// frontend/src/views/Login.vue
<template>
  <div class="flex min-h-[calc(100vh-12rem)] items-center justify-center py-10">
    <div class="grid w-full max-w-6xl gap-6 lg:grid-cols-[1.1fr_0.9fr]">
      <section class="hidden overflow-hidden rounded-[36px] border border-white/10 bg-[linear-gradient(135deg,rgba(255,67,163,0.14),rgba(245,134,52,0.12)_34%,rgba(17,15,16,0.96)_72%)] p-10 shadow-2xl shadow-black/30 lg:block">
        <div class="flex h-full flex-col justify-between">
          <div>
            <p class="text-xs uppercase tracking-[0.45em] text-brand-pink">Morena Concept</p>
            <h1 class="mt-6 max-w-xl font-display text-6xl leading-[0.95] text-white">
              Imagine a Place com uma operação à altura da marca.
            </h1>
            <p class="mt-6 max-w-lg text-base leading-7 text-white/70">
              Painel redesenhado com atmosfera escura, contraste sofisticado e a paleta oficial do brandbook aplicada em toda a experiencia.
            </p>
          </div>

          <div class="grid grid-cols-3 gap-4">
            <div class="brand-card-soft rounded-[24px] p-4">
              <p class="text-xs uppercase tracking-[0.32em] text-white/40">Base</p>
              <p class="mt-3 font-display text-3xl text-white">#373435</p>
            </div>
            <div class="brand-card-soft rounded-[24px] p-4">
              <p class="text-xs uppercase tracking-[0.32em] text-white/40">Accent</p>
              <p class="mt-3 font-display text-3xl text-brand-pink">#FF43A3</p>
            </div>
            <div class="brand-card-soft rounded-[24px] p-4">
              <p class="text-xs uppercase tracking-[0.32em] text-white/40">Energy</p>
              <p class="mt-3 font-display text-3xl text-brand-orange">#F58634</p>
            </div>
          </div>
        </div>
      </section>

      <section class="brand-card rounded-[32px] p-8 sm:p-10">
        <div class="mb-10">
          <Logo />
          <p class="mt-6 text-xs uppercase tracking-[0.35em] text-brand-pink">Sistema ERP</p>
          <h2 class="mt-4 font-display text-5xl text-white">Entrar</h2>
          <p class="mt-3 text-sm leading-6 text-white/60">
            Use as credenciais configuradas no backend para acessar a operação da marca.
          </p>
        </div>

        <Alert
          v-if="error"
          :message="error"
          type="error"
          @close="error = null"
        />

        <form @submit.prevent="handleLogin" class="space-y-4">
          <div>
            <label class="mb-2 block text-xs font-bold uppercase tracking-[0.26em] text-white/60">Email</label>
            <input
              v-model="credentials.email"
              type="email"
              required
              placeholder="seu@email.com"
              class="brand-input w-full rounded-2xl px-4 py-4"
            />
          </div>

          <div>
            <label class="mb-2 block text-xs font-bold uppercase tracking-[0.26em] text-white/60">Senha</label>
            <input
              v-model="credentials.password"
              type="password"
              required
              placeholder="********"
              class="brand-input w-full rounded-2xl px-4 py-4"
            />
          </div>

          <button
            type="submit"
            :disabled="loading"
            class="brand-button-primary mt-4 w-full rounded-2xl py-4 text-sm font-bold uppercase tracking-[0.24em] transition disabled:opacity-50"
          >
            {{ loading ? 'Conectando' : 'Acessar painel' }}
          </button>
        </form>

        <div class="mt-8 rounded-[24px] border border-white/10 bg-white/5 p-5">
          <p class="text-xs uppercase tracking-[0.3em] text-brand-gray">Identidade aplicada</p>
          <p class="mt-3 text-sm leading-6 text-white/60">
            Logo, tagline e atmosfera visual alinhadas ao brandbook da MORENA CONCEPT, agora com leitura mais premium e contraste mais escuro.
          </p>
        </div>
      </section>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import Alert from '../components/Alert.vue'
import Logo from '../components/Logo.vue'
import { authAPI } from '../api/client'
import { useAuthStore } from '../stores/authStore'

const router = useRouter()
const authStore = useAuthStore()

const credentials = ref({
  email: '',
  password: ''
})

const error = ref(null)
const loading = ref(false)

const handleLogin = async () => {
  error.value = null
  loading.value = true

  try {
    const response = await authAPI.login(credentials.value)
    authStore.setToken(response.data.access_token)
    authStore.setUser(response.data.user)
    await router.push('/dashboard')
  } catch (err) {
    error.value = `Erro ao fazer login: ${err.response?.data?.detail || err.message || 'Verifique suas credenciais'}`
  } finally {
    loading.value = false
  }
}
</script>

// frontend/src/views/Login.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Grid,
  Box,
  Typography,
  Card,
  TextField,
  Button,
  Alert,
} from '@mui/material';
import { useAuth } from '../context/AuthContext';

const Login: React.FC = () => {
  const { login, isAuthenticated } = useAuth();
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  React.useEffect(() => {
    if (isAuthenticated) {
      navigate('/dashboard');
    }
  }, [isAuthenticated, navigate]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setLoading(true);

    try {
      await login({ email, password });
      navigate('/dashboard');
    } catch (err: any) {
      setError(
        `Erro ao fazer login: ${err.response?.data?.detail || err.message || 'Verifique suas credenciais'}`
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <Box
      sx={{
        display: 'flex',
        minHeight: '80vh',
        alignItems: 'center',
        justifyContent: 'center',
        py: 4,
      }}
    >
      <Grid container spacing={4} sx={{ maxWidth: '1100px', width: '100%' }}>
        {/* Left column - Branding Info */}
        <Grid item xs={12} lg={6.5} sx={{ display: { xs: 'none', lg: 'block' } }}>
          <Box
            sx={{
              height: '100%',
              borderRadius: '36px',
              border: '1px solid rgba(255, 255, 255, 0.1)',
              background:
                'linear-gradient(135deg, rgba(255, 67, 163, 0.14), rgba(245, 134, 52, 0.12) 34%, rgba(17, 15, 16, 0.96) 72%)',
              p: 6,
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'space-between',
              boxShadow: '0 20px 40px rgba(0, 0, 0, 0.3)',
            }}
          >
            <Box>
              <Typography
                sx={{
                  fontSize: '0.75rem',
                  textTransform: 'uppercase',
                  letterSpacing: '0.45em',
                  color: '#FF43A3',
                  fontWeight: 700,
                }}
              >
                Morena Concept
              </Typography>
              <Typography
                variant="h1"
                sx={{
                  mt: 4,
                  fontSize: '3.5rem',
                  lineHeight: 1.05,
                  color: '#ffffff',
                }}
              >
                Imagine a Place com uma operação à altura da marca.
              </Typography>
              <Typography
                variant="body1"
                sx={{
                  mt: 3,
                  color: 'rgba(255, 255, 255, 0.7)',
                  lineHeight: 1.7,
                }}
              >
                Painel redesenhado com atmosfera escura, contraste sofisticado e a paleta oficial do brandbook aplicada em toda a experiência.
              </Typography>
            </Box>

            <Grid container spacing={2}>
              <Grid item xs={4}>
                <Box
                  sx={{
                    borderRadius: '24px',
                    border: '1px solid rgba(255, 255, 255, 0.06)',
                    background: 'linear-gradient(180deg, rgba(48, 42, 45, 0.92), rgba(28, 24, 26, 0.94))',
                    p: 2.5,
                  }}
                >
                  <Typography variant="caption" sx={{ textTransform: 'uppercase', letterSpacing: '0.32em', color: 'rgba(255, 255, 255, 0.4)' }}>
                    Base
                  </Typography>
                  <Typography variant="h5" sx={{ mt: 1.5, color: '#ffffff' }}>
                    #373435
                  </Typography>
                </Box>
              </Grid>
              <Grid item xs={4}>
                <Box
                  sx={{
                    borderRadius: '24px',
                    border: '1px solid rgba(255, 255, 255, 0.06)',
                    background: 'linear-gradient(180deg, rgba(48, 42, 45, 0.92), rgba(28, 24, 26, 0.94))',
                    p: 2.5,
                  }}
                >
                  <Typography variant="caption" sx={{ textTransform: 'uppercase', letterSpacing: '0.32em', color: 'rgba(255, 255, 255, 0.4)' }}>
                    Accent
                  </Typography>
                  <Typography variant="h5" sx={{ mt: 1.5, color: '#FF43A3' }}>
                    #FF43A3
                  </Typography>
                </Box>
              </Grid>
              <Grid item xs={4}>
                <Box
                  sx={{
                    borderRadius: '24px',
                    border: '1px solid rgba(255, 255, 255, 0.06)',
                    background: 'linear-gradient(180deg, rgba(48, 42, 45, 0.92), rgba(28, 24, 26, 0.94))',
                    p: 2.5,
                  }}
                >
                  <Typography variant="caption" sx={{ textTransform: 'uppercase', letterSpacing: '0.32em', color: 'rgba(255, 255, 255, 0.4)' }}>
                    Energy
                  </Typography>
                  <Typography variant="h5" sx={{ mt: 1.5, color: '#F58634' }}>
                    #F58634
                  </Typography>
                </Box>
              </Grid>
            </Grid>
          </Box>
        </Grid>

        {/* Right column - Login Form Card */}
        <Grid item xs={12} lg={5.5}>
          <Card sx={{ p: { xs: 4, sm: 5 }, height: '100%', display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
            <Box sx={{ mb: 5 }}>
              <Typography
                sx={{
                  fontSize: '0.75rem',
                  textTransform: 'uppercase',
                  letterSpacing: '0.35em',
                  color: '#FF43A3',
                  fontWeight: 700,
                }}
              >
                Sistema ERP
              </Typography>
              <Typography variant="h3" sx={{ mt: 2, fontSize: '2.5rem', color: '#ffffff' }}>
                Entrar
              </Typography>
              <Typography variant="body2" sx={{ mt: 1.5, color: 'text.secondary', lineHeight: 1.6 }}>
                Use as credenciais configuradas no backend para acessar a operação da marca.
              </Typography>
            </Box>

            {error && (
              <Alert severity="error" sx={{ mb: 4, borderRadius: '16px' }} onClose={() => setError(null)}>
                {error}
              </Alert>
            )}

            <form onSubmit={handleSubmit}>
              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
                <Box>
                  <Typography
                    sx={{
                      mb: 1,
                      fontSize: '0.7rem',
                      fontWeight: 700,
                      textTransform: 'uppercase',
                      letterSpacing: '0.26em',
                      color: 'rgba(255, 255, 255, 0.6)',
                    }}
                  >
                    Email
                  </Typography>
                  <TextField
                    fullWidth
                    variant="outlined"
                    type="email"
                    required
                    placeholder="seu@email.com"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                  />
                </Box>

                <Box>
                  <Typography
                    sx={{
                      mb: 1,
                      fontSize: '0.7rem',
                      fontWeight: 700,
                      textTransform: 'uppercase',
                      letterSpacing: '0.26em',
                      color: 'rgba(255, 255, 255, 0.6)',
                    }}
                  >
                    Senha
                  </Typography>
                  <TextField
                    fullWidth
                    variant="outlined"
                    type="password"
                    required
                    placeholder="********"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                  />
                </Box>

                <Button
                  fullWidth
                  variant="contained"
                  type="submit"
                  disabled={loading}
                  sx={{
                    mt: 2,
                    py: 1.8,
                    borderRadius: '16px',
                  }}
                >
                  {loading ? 'Conectando...' : 'Acessar painel'}
                </Button>
              </Box>
            </form>

            <Box
              sx={{
                mt: 4,
                borderRadius: '24px',
                border: '1px solid rgba(255, 255, 255, 0.1)',
                background: 'rgba(255, 255, 255, 0.03)',
                p: 3,
              }}
            >
              <Typography
                sx={{
                  fontSize: '0.65rem',
                  textTransform: 'uppercase',
                  letterSpacing: '0.3em',
                  color: 'text.secondary',
                  fontWeight: 700,
                }}
              >
                Identidade aplicada
              </Typography>
              <Typography variant="body2" sx={{ mt: 1, color: 'rgba(255,255,255,0.6)', lineHeight: 1.6 }}>
                Logo, tagline e atmosfera visual alinhadas ao brandbook da MORENA CONCEPT, agora com leitura mais premium e contraste mais escuro.
              </Typography>
            </Box>
          </Card>
        </Grid>
      </Grid>
    </Box>
  );
};

export default Login;
